print("moi ban nhap vao canh hinh chu nhat ")
a=int (input("a"))
print("Bạn nhập cạnh a=:",a)
b=int(input("b"))
print("Bạn nhập cạnh b=:",b)
print("chu vi ", (a+b*2))
print("dien tích", a*b)
print("chu vi",(a+b)*2,end='*')#tiếp chuỗi
print("dien tich",a*b)

# from turtle import *
# for v in range(100)
#     forward(100)
#     left(90)
#      forward(100)
#     left(90)
#      forward(100)
#     left(90)
#      forward(100)
#     left(90)
#     left(90)
